services:
  db_offer:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_offer
    volumes:
      - donnees:/var/lib/mysql
    networks:
      - app-network
  job-backend:
    build:
      context: ./job-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_offer:3306/db_offer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db_offer
    networks:
      - app-network
  job-frontend:
    build:
      context: ./job-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - job-backend
    environment:
      REMOTE_HOST: http://job-backend:8084
    networks:
      - app-network
volumes:
  donnees:
networks:
  app-network:
    driver: bridge


