apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jobmatch
  name: job-backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://db-offer:3306/db_offer?createDatabaseIfNotExist=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
  SPRING_DATASOURCE_USERNAME: root
