apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jobmatch
  labels:
    app: job-backend
spec:
  selector:
    app: job-backend
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP
