apiVersion: v1
kind: Service
metadata:
  name: job-frontend
  labels:
    app: job-frontend
spec:
  selector:
    app: job-frontend
  ports:
    - name: http
      port: 4200
      targetPort: 80
      protocol: TCP
  type: NodePort
