apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - backend-configmap.yaml
  - job-backend-deployment.yaml
  - job-backend-service.yaml
  - frontend-configmap.yaml
  - job-frontend-deployment.yaml
  - job-frontend-service.yaml
  - ingress.yaml

images:
  - name: ./job-backend
    newTag: latest
  - name: ./job-frontend
    newTag: latest
