apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: jobmatch

  labels:
    app: db-offer
spec:
  selector:
    app: db-offer
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
